FROM maven:3.8.3-openjdk-17 as builder
WORKDIR /cantieri
COPY . /cantieri
RUN mvn clean install -Dmaven.test.skip=true

FROM openjdk:17-alpine

COPY --from=builder /cantieri/target/cantieri-0.0.1-SNAPSHOT.jar ./

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "cantieri-0.0.1-SNAPSHOT.jar"]