version: '3.8'
name: my_app
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d

volumes:
  db:
    driver: local
